[workspace]
authors = ["Sheona Hans <sheonahans@gmail.com>"]
channels = ["conda-forge"]
name = "BINF-5507-Materials"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
matplotlib = ">=3.10.3,<4"
scikit-learn = ">=1.6.1,<2"
seaborn = ">=0.13.2,<0.14"
ipykernel = ">=6.29.5,<7"
